# Generated by Django 4.1.7 on 2023-02-26 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reservation_slot',
            field=models.SmallIntegerField(choices=[(datetime.time(14, 0), '14:00:00'), (datetime.time(15, 0), '15:00:00'), (datetime.time(16, 0), '16:00:00'), (datetime.time(17, 0), '17:00:00'), (datetime.time(18, 0), '18:00:00'), (datetime.time(19, 0), '19:00:00'), (datetime.time(20, 0), '20:00:00'), (datetime.time(21, 0), '21:00:00'), (datetime.time(22, 0), '22:00:00')], default=10),
        ),
    ]
